In [18]:
'''
Implement the Image classification CNN model for classifying hand-written MNIST dataset by dividing the model into following 4 stages:
a.	Loading and preprocessing the image data
b.	Defining the model's architecture
c.	Training the model
d.	Estimating the model's performance
'''

"\nImplement the Image classification CNN model for classifying hand-written MNIST dataset by dividing the model into following 4 stages:\na.\tLoading and preprocessing the image data\nb.\tDefining the model's architecture\nc.\tTraining the model\nd.\tEstimating the model's performance\n"

In [19]:
import pandas as pd
import numpy as  np
import matplotlib.pyplot as plt

import seaborn as sns
import tensorflow as tf
from tensorflow.keras.layers import BatchNormalization, Conv2D, Dense, Dropout, MaxPooling2D, Flatten
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.optimizers import SGD

In [20]:
# Load the training and testing data from CSV files
train = pd.read_csv("/home/tanisha/DL/LP-IV-datasets/MNIST(Ass2&3)/mnist_train.csv")
train

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59996,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59997,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59999,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
x_train = train.drop(['label'], axis = 1).values
y_train = train['label'].values
x_train.shape

(60000, 784)

In [22]:
x_train = x_train.reshape((60000, 28, 28, 1)).astype('float32')/255
x_train.shape

(60000, 28, 28, 1)

In [35]:
test = pd.read_csv("/home/tanisha/DL/LP-IV-datasets/MNIST(Ass2&3)/mnist_test.csv")
test

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9999,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [37]:

x_test = test.drop(['label'], axis = 1).values
y_test = test['label'].values
x_test = x_test.reshape((10000, 28, 28, 1)).astype('float32')/255

x_test.shape

(10000, 28, 28, 1)

In [38]:
model = Sequential()
model.add(Conv2D(32, (3,3), input_shape = (28, 28, 1), activation = 'relu'))
model.add(BatchNormalization())
model.add(Conv2D(64, (3,3),activation = 'relu'))
model.add(MaxPooling2D((2,2)))
model.add(Flatten())
model.add(Dense(64, activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(10, activation = 'softmax'))

sgd = SGD(learning_rate = 0.1)
model.compile(optimizer= sgd, loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d_4 (Conv2D)           (None, 26, 26, 32)        320

 batch_normalization_2 (Bat  (None, 26, 26, 32)        128
 chNormalization)

 conv2d_5 (Conv2D)           (None, 24, 24, 64)        18496

 max_pooling2d_2 (MaxPoolin  (None, 12, 12, 64)        0
 g2D)

 flatten_2 (Flatten)         (None, 9216)              0

 dense_4 (Dense)             (None, 64)                589888

 dropout_2 (Dropout)         (None, 64)                0

 dense_5 (Dense)             (None, 10)                650

=================================================================
Total params: 609482 (2.32 MB)
Trainable params: 609418 (2.32 MB)
Non-trainable params: 64 (256.00 Byte)
_________________________________________________________________

In [ ]:
r = model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs = 3, batch_size = 64)

Epoch 1/3
938/938 [==============================] - 63s 66ms/step - loss: 0.2853 - accuracy: 0.9139 - val_loss: 0.0653 - val_accuracy: 0.9794
Epoch 2/3
938/938 [==============================] - 54s 58ms/step - loss: 0.0896 - accuracy: 0.9733 - val_loss: 0.0474 - val_accuracy: 0.9841
Epoch 3/3
293/938 [========>.....................] - ETA: 36s - loss: 0.0679 - accuracy: 0.9792

In [ ]:
predictions = model.predict(x_test)

In [ ]:
predictions

In [ ]:
r.history.keys()

In [ ]:
test_loss, test_accuracy = model.evaluate(x_test, y_test)
print(f'Test Loss: {test_loss:.4f}')
print(f'Test Accuracy: {test_accuracy:.4f}')

In [ ]:

plt.plot(r.history['accuracy'], label = 'accuracy', color = 'green')
plt.plot(r.history['val_accuracy'], label = 'val_accuracy', color = 'red')
plt.legend()

In [ ]:
plt.plot(r.history['loss'], label = 'loss', color = 'red')
plt.plot(r.history['val_loss'], label = 'val_loss', color = 'blue')
plt.legend()